version: '1.2'
services: 
  zap:
    container_name: zap-container
    build: 
        context: ./docker/zap
        dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - C:\Users\Karthick\Documents\Concord\Learning\travelix:C:\zap\reports
    depends_on:
      - web
    networks:
      - zap-network

  web:
    build: .
    container_name: web
    ports:
      - "3000:3000"
    networks:
      - zap-network
  
networks:
  zap-network: 
  
# version: '1'
# services: 
#   zap:
#     image: ghcr.io/zaproxy/zaproxy:stable
#     image: webpwnized/mutillidae:database
#     container_name: zap
#     ports:
#       - "4000:80"
#     entrypoint: ["zap.sh", "-daemon", "-port", "4000", "-host", "0.0.0.0", "-config", "api.addrs.addr.name=.*", "-config", "api.addrs.addr.regex=true", "-config", "api.disablekey=true"]
#     volumes:
#       - ./zap:/zap/wrk:rw
#     environment:
#       - ZAP_HOMEDIR=/zap/home
#     networks:
#       - zap-network
  
#   web:
#     build: .
#     container_name: web
#     ports:
#       - "3000:80"
#     depends_on:
#       - zap
#     networks:
#       - zap-network

# networks:
#   zap-network:
#     driver: bridge
