pipeline {
    agent any

    environment {
        CI = 'false'
        IMAGE_NAME = 'travelix'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${env.BUILD_ID}")
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    // Stop and remove any existing container with the same name
                    // try {
                    //     sh "docker stop react_app"
                    //     sh "docker rm react_app"
                    // } catch (Exception e) {
                    //     echo 'No existing container to remove.'
                    // }

                    // Run the new container
                    docker.image("${IMAGE_NAME}:${env.BUILD_ID}").run('-d --name travelix -p 3000:80')
                }
            }
        }
        // stage('Install Dependencies') {
        //     steps {
        //         nodejs('NodeJS') {
        //             bat 'npm install'
        //         }
        //     }
        // }
        // stage('Run Tests') {
        //     steps {
        //         nodejs('NodeJS') {
        //             bat 'npm test -- --coverage --watchAll=false --passWithNoTests'
        //         }
        //     }
        // }
        // stage('Build') {
        //     steps {
        //         nodejs('NodeJS') {
        //             bat 'npm run build'
        //         }
        //     }
        // }
    }
}